language: python
sudo: false
python:
  - "3.6"
  - "3.7-dev"
  - "nightly"

install:
  - "python setup.py install"
  - "pip install pytest"

script: "py.test --doctest-module --ignore=setup.py --doctest-glob='*.rst'"
